### ISSUE TITLE
No importlib.machinery in py2.7

### ISSUE THREAD

**Issue by stuaxo** [brettcannon/importlib#1]
Hi,
   I've made a project https://github.com/stuaxo/vext that allows you to import certain modules from the system python into a virtualenv.

It works by using imp.find_module and imp.load_module.

At the moment it works with python2 via ```imp``` I'd like to port it to python 3 and have a lot of shared code - it seems that the equivilents are in importlib.machinery ... I would use these instead, but they aren't available in python2 .. .   so it looks like I have to have different code for py2 and py3 ... is that the case  - or is there any way that importlib.machinery could get into python2.7.x ?

**Comment by brettcannon** [comment]
Someone has backported importlib to Python 2.7 at https://pypi.python.org/pypi/importlib2 . You can also keep using imp in Python 3 and simply silence the deprecation.

**Comment by stuaxo** [comment]
Cheers, will give importlib2 a go, not keen on using the deprecated API :)

**Comment by nschloe** [comment]
FYI, the backport doesn't work with `machinery`; cf. https://bitbucket.org/ericsnowcurrently/importlib2/issues/8/unable-to-import-importlib2machinery.
