### ISSUE TITLE
Missing `importlib/__init__.py` in repo?

### ISSUE THREAD

**Issue by jakirkham** [brettcannon/importlib#3]
Appears that `importlib/__init__.py` is missing from the repo. Would be nice if it was included.

**Comment by jakirkham** [comment]
Oddly enough this seems to be [intentional]( https://github.com/brettcannon/importlib/blob/83ad2bdf5b1bd68482df33209dfe4d7049f39f63/.gitignore#L1 ).

**Comment by brettcannon** [comment]
It is as the files are literally copied over from importlib in Python 2.7 so that the code doesn't accidentally fork. This repo is literally just to keep the files necessary for building the sdist and related packages.

**Comment by jakirkham** [comment]
Makes sense. Thanks for clarifying.
